# Welcome to Codejoy!

# Site settings
title: Code.Joy
subtitle: "개발자가 되려던 건 아니었습니다만... 어쩌다 개발까지 하게 된 일당백 현대인의 기록"
email: codejoy.seyoon@gmail.com
url: "https://codejoy-seyoon.github.io"
baseurl: ""
repository: "codejoy-seyoon/codejoy-seyoon.github.io"
description: >-
  개발자가 되려던 건 아니었습니다만... 어쩌다 개발까지 하게 된 일당백 현대인의 기록
github_username: codejoy-seyoon
minimal_mistakes_skin: default
search: true
locale: ko-KR

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.28.1
# Outputting
permalink: /posts/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "seyoon"
  bio    : "기획.시스템 빌더<br>특기 : 어떻게든 되게 만들기"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/codejoy-seyoon"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:codejoy.seyoon@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/codejoy-seyoon"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/